spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

eun1:
  riot:
    url: "https://eun1.api.riotgames.com/lol"

europe:
  riot:
    url: "https://europe.api.riotgames.com/"

ddragon:
  url: "https://ddragon.leagueoflegends.com/"

api:
  key: "x:/key.txt"