spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

api:
  key: " "
  riot:
    url: "https://eun1.api.riotgames.com/lol"
masala:
  puuid: "zZdUMg3S_AZOxr8sZ4eVo-ge5MKWsA6L2GY8xWHgyi7un2XfRbNvcytY4Zi2iDila9BuyEbUxBEfMg"

ddragon:
  url: "https://ddragon.leagueoflegends.com/cdn/"
  version: "https://ddragon.leagueoflegends.com/api/versions.json"
